name: clean_flutter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  faker: ^2.0.0
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  test: null

flutter:
  uses-material-design: true
